-- Phase 2: cached poem insights generated by Cloudflare Workers AI.
-- One row per (poem_id). User-specific insights can be added later when
-- personalisation requires it.
CREATE TABLE IF NOT EXISTS insights (
  id TEXT PRIMARY KEY,
  poem_id TEXT NOT NULL,
  translation TEXT NOT NULL,
  context TEXT NOT NULL,
  themes TEXT NOT NULL,
  model TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_insights_poem ON insights(poem_id);

-- Helps the users.email lookup for /api/auth/login (already unique, but
-- indexing avoids full table scans as the user base grows).
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
